language: objective-c
xcode_project: PromiseKit.xcodeproj
xcode_scheme: [PMKiOS, PMKOSX]
xcode_sdk: [iphonesimulator9.3, macosx10.11]
osx_image: xcode7.3

install:
  - gem install travis-xcodebuild
  - carthage bootstrap

script:
  - travis-xcodebuild

matrix:
  exclude:
    - xcode_scheme: PMKOSX
      xcode_sdk: iphonesimulator9.3
    - xcode_scheme: PMKiOS
      xcode_sdk: macosx10.11

branches:
  only:
    - master
    - swift-2.2-minimal-changes
    - swift-2.0-minimal-changes
    - legacy-1.x
